pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                withCredentials([string(credentialsId: 'github-pat', variable: 'pat')]) {
                    git branch: 'main', url: "https://${pat}@github.com/k3rcaft/java-azure-integration-api.git"
                }
            }
        }
        stage('Build') {
            steps {
                sh "./gradlew clean build"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying..'
            }
        }
    }
}
